name: ci

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/setup-node@v4
        name: Setup Node
        with:
          cache: npm
          cache-dependency-path: client/package-lock.json

      - run: npm install
        name: npm Install
        working-directory: client

      - run: npm run build
        name: npm Build
        working-directory: client

      - run: npx biome check
        name: biome check
        working-directory: client
